---
title: "workspace"
author: "Linnéa Smeds"
output: html_document
---

# 1 Setting up
```{r}
renv::install("vcfR")
require(vcfR)
require(tidyverse)
renv::install("tictoc")
require(tictoc)

```

# 2. Reading in the data
```{r}
tic()
vcf_file="data/Wolf.deleterious.missense.polarized.vcf"
pop_file="data/5TempClasses11I95F15R.pop.list"
vcf <- read.vcfR(vcf_file)
pop_table<-read.table(pop_file, header = FALSE, sep = "\t")
pop_tib<-as_tibble(pop_table) %>% rename(Indiv=V1, Pop=V2)
pop <- as.factor(pop_table$V2)
toc()
#7.417 sec (EBC)
#7.442 sec (home)
```

## 2.1 Convert to tidy format
```{r}
tic()
tidy_vcf <- vcfR2tidy(vcf, 
                      info_fields=c("AA"), 
                      format_fields=c("GT"), 
                      dot_is_NA=TRUE)
toc()
# 8.265 sec (EBC)
# 10.046 sec (home)
```
## 2.2 Investigating tidy format
```{r}
# there are three separate tables, the gt one is over 1M rows
head(tidy_vcf)

# checking how often ancestral is reference
okpos<- tidy_vcf$fix %>%filter(REF==AA)
# and the opposite, ancestral is alternative (needs flipping!)
invertpos<-tidy_vcf$fix %>%filter(ALT==AA)
```

## 2.2 Extracting relevant data 
### 2.2.1 Trial 1
```{r}
tic()
# REF is ANCESTRAL
# 0/0 
homref_aa_ref<-tidy_vcf$gt %>% inner_join(okpos) %>% filter(gt_GT=="0/0") %>% group_by(Indiv) %>%summarize(num_homref_aa=n())
# 1/1
homalt_aa_ref<-tidy_vcf$gt %>% inner_join(okpos) %>% filter(gt_GT=="1/1") %>% group_by(Indiv) %>%summarize(num_homalt_der=n())
# ALT is ANCESTRAL
#0/0
homref_aa_alt<-tidy_vcf$gt %>% inner_join(invertpos) %>% filter(gt_GT=="0/0") %>% group_by(Indiv) %>%summarize(num_homref_der=n())
# 1/1
homalt_aa_alt<-tidy_vcf$gt %>% inner_join(invertpos) %>% filter(gt_GT=="1/1") %>% group_by(Indiv) %>%summarize(num_homalt_aa=n())
# merge above
aa_tib<- homref_aa_ref %>% inner_join(homalt_aa_alt) %>% mutate(num_aa=num_homref_aa+num_homalt_aa) %>% select(Indiv, num_aa)
der_tib<-homalt_aa_ref %>% inner_join(homref_aa_alt) %>% mutate(num_der=num_homref_der+num_homalt_der) %>% select(Indiv, num_der)

# For heterozygous sites, AA doesn't matter
#0/1
het<-tidy_vcf$gt %>% filter(gt_GT=="0/1") %>% group_by(Indiv) %>%summarize(num_het=n())

# merge everything
tidy_gt<-aa_tib %>% inner_join(het) %>% inner_join(der_tib) 
toc()
# 1.404 sec (home)
#4.072sec
```

###2.2.2 Trial 2
```{r}
tic()
# ref is ancestral
refAA_tib<-tidy_vcf$gt %>% filter(!is.na(gt_GT)) %>% inner_join(okpos) %>% group_by(Indiv, gt_GT) %>% summarize(count=n()) %>% ungroup() %>% mutate(gt = case_when(gt_GT=='0/0' ~ 'refAA_homanc', gt_GT=='0/1' ~'refAA_het', gt_GT=='1/1' ~'refAA_homder')) %>% select(-gt_GT) %>% pivot_wider(names_from=gt, values_from=count)
# ref is derived
altAA_tib<-tidy_vcf$gt %>% filter(!is.na(gt_GT)) %>% inner_join(invertpos) %>% group_by(Indiv, gt_GT) %>% summarize(count=n()) %>% ungroup() %>% mutate(gt = case_when(gt_GT=='0/0' ~ 'altAA_homder', gt_GT=='0/1' ~'altAA_het', gt_GT=='1/1' ~'altAA_homanc')) %>% select(-gt_GT) %>% pivot_wider(names_from=gt, values_from=count)
# merge
tidy_gt2 <- refAA_tib %>% inner_join(altAA_tib) %>% transmute(Indiv, num_aa=altAA_homanc+refAA_homanc, num_het=refAA_het+altAA_het, num_der=refAA_homder+altAA_homder) 
toc()
#2.521 sec (EBC)
#0.993 sec (home)
```
###2.2.3 Trial 3 - Best version!
```{r}
tic()
tidy_gt3<-tidy_vcf$gt %>% filter(!is.na(gt_GT)) %>% inner_join(tidy_vcf$fix)  %>% mutate(new_gt=case_when((ALT==AA & gt_GT=='0/0') ~'1/1', (ALT==AA & gt_GT=='1/1') ~'0/0', TRUE ~ gt_GT)) %>% group_by(Indiv, new_gt) %>% summarize(count=n()) %>% ungroup() %>% mutate_if(is.character, str_replace_all, pattern = "/", replacement = "") %>% pivot_wider(names_from=new_gt, names_prefix="gt", values_from=count)
toc()
#1.622 sec (EBC)
#0.691 sec (home)

#Add population names and some extra columns to facilitate plotting!
final_gt<- tidy_gt3 %>% mutate(sum=gt00+gt01+gt11) %>% inner_join(pop_tib) %>% mutate(hetfrq=gt01/sum, homderfrq=gt11/sum, deralfreq=(gt11*2+gt01)/(sum*2),Grp=case_when(Pop=='Finland' | Pop=='Russia' ~ Pop, TRUE ~ 'Scandinavia')) 
```


# 3. Analysis / Plots
##3.1 Boxplots
###3.1.1 First try: boxes and points
```{r}
ggplot(final_gt,aes(Pop,hetfrq))+
  geom_boxplot(aes(fill=Pop))+
    geom_point() +
    labs(x=NULL,y="proportion heterozygous sites")+
    theme(axis.text.x=element_blank(),
        axis.ticks.x=element_blank())


```
### 3.1.2 Geometric jitter
```{r}
ggplot(final_gt,aes(Pop,homderfrq))+
  geom_jitter(aes(color=Pop),alpha=0.3) +
  labs(x=NULL,y="proportion heterozygous sites")
# This doesn't look good at all, too few points per class!
```
### 3.1.3 Reorder boxes (using factors)
```{r}
# add factors to pop and order as I want
final_gt$Pop <- factor(final_gt$Pop, levels = c("1983-1990", "1991-1998", "1999-2006", "2007-2014S", "2007-2014I", "Immigrant", "Finland", "Russia"))
ggplot(final_gt,aes(Pop, hetfrq))+
  geom_boxplot(aes(fill=Pop))+
  geom_point() +
  labs(x=NULL,y="proportion heterozygous sites")+
  theme(legend.title=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank())
```
###3.1.4 Try facet
```{r}
ggplot(final_gt,aes(Pop, hetfrq))+
  geom_boxplot(aes(fill=Pop))+
  geom_point() +
  facet_grid(~factor(Grp, level=c("Scandinavia", "Finland", "Russia")), scales="free_x", space="free_x") +
  labs(x=NULL,y="proportion heterozygous sites")+
  theme(legend.title=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank())
```
###3.1.4 Violin, colours etc
```{r}
ggplot(final_gt,aes(Pop, hetfrq))+
  geom_violin(aes(fill=Pop))+
  geom_point() +
  scale_fill_viridis(discrete=TRUE) +
  facet_grid(~factor(Grp, level=c("Scandinavia", "Finland", "Russia")), scales="free_x", space="free_x") +
  labs(x=NULL,y="proportion heterozygous sites")+
  theme(panel.grid.major = element_line(colour = 'white'),
        panel.background = element_rect(fill = '#f5f4e6', colour = '#FFFDF8'),
        legend.title=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank())
```

